name: karpuz
description: Karpuz - Meyve Birleştirme Oyunu
publish_to: 'none'
version: 1.0.51+51

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/game.html
