name: karpuz
description: Karpuz - Meyve Birleştirme Oyunu
publish_to: 'none'
version: 1.0.122+122

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.0
  webview_flutter_android: ^3.16.0
  http: ^1.2.0
  url_launcher: ^6.2.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/game.html
